# Generated by Django 3.0.2 on 2020-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('firmware', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('server', models.ForeignKey(on_delete=models.SET('None'), to='inventory.Server')),
                ('switch', models.ForeignKey(on_delete=models.SET('None'), to='inventory.Switch')),
            ],
        ),
    ]
