# Generated by Django 3.0.2 on 2020-01-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='doug_vrx', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='sw_version',
            field=models.CharField(default=5.2, max_length=200, verbose_name='Software version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='switch',
            name='path',
            field=models.CharField(max_length=50),
        ),
    ]
