# Generated by Django 3.0.2 on 2020-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200129_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(max_length=200, unique=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(blank=True, on_delete=models.SET('None'), to='inventory.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
